TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.Form': true
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.Form': ['Main', 'Forms', 'Modules', 'NodeTypes/*']
    modules:
      administration:
        submodules:
          form:
            label: 'Dotpulse.Form:Modules:form.label'
            controller: '\Dotpulse\Form\Controller\Module\FormController'
            description: 'Dotpulse.Form:Modules:form.description'
            icon: 'icon-envelope-alt'
            resource: 'Dotpulse.Form:Backend.Module.Form'

  Form:
    yamlPersistenceManager:
      savePath: 'resource://Dotpulse.Form/Private/Forms/'
    presets:
      default:
        title: 'Dotpulse'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Dotpulse.Form/Private/Layouts/Default/{@type}.html'
              partialPathPattern: 'resource://Dotpulse.Form/Private/Partials/Default/{@type}.html'
              translationPackage: 'Dotpulse.Form'
              translationErrorPackage: 'TYPO3.Flow'
          #'TYPO3.Form:Page':
          #  renderingOptions:
          #    templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/Page.html'
          #'TYPO3.Form:Section':
          #  properties:
          #    rowClassAttribute: 'row'
          #    colClassAttribute: 'col-sm-6'
          #    colRenderPosition: FALSE # possible options: first || last
          #  renderingOptions:
          #    templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/Section.html'
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/Form.html'
              containerClassAttribute: ''
              multipartForm: FALSE
              renderSubmitButton: TRUE
              buttonContainerClass: 'actions'
              previousButtonClass: 'btn btn-cancel'
              nextButtonClass: 'btn btn-primary'
              submitButtonClass: 'btn btn-primary'
          'TYPO3.Form:FormElement':
            properties:
              containerClassAttribute: 'clearfix'
              errorClassAttribute: 'error'
              renderLabel: TRUE
              rowClassAttribute: 'row'
              colClassAttribute: 'col-sm-6'
              colElement: FALSE # possible options: first || middle || last
              #requiredClassAttribute: 'val-required'
              #tooltipClass: 'white-popup mfp-hide'
              #tooltipIconClass: 'fa fa-question-circle'
          'TYPO3.Form:SingleLineText':
            properties:
              elementClassAttribute: ''
              type: 'text'
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/SingleLineText.html'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: 'xxlarge'
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/MultiLineText.html'
          'TYPO3.Form:SingleSelectDropdown':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/SingleSelectDropdown.html'
          'Dotpulse.Form:Submit':
            superTypes:
              'TYPO3.Form:FormElement': TRUE
              'TYPO3.Form:TextMixin': TRUE
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/Submit.html'
            properties:
              containerClassAttribute: 'clearfix'
              elementClassAttribute: 'btn btn-primary'
          'Dotpulse.Form:Column':
            superTypes:
              'TYPO3.Form:FormElement': TRUE
            implementationClassName: 'TYPO3\Form\FormElements\Section'
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Default/Column.html'
              renderableNameInTemplate: 'section'
            properties:
              rowClassAttribute: 'row'
              colClassAttribute: 'col-sm-6'
              colRenderPosition: FALSE # possible options: first || last

        finisherPresets:
          'TYPO3.Form:Email':
            options:
              templatePathAndFilename: 'resource://Dotpulse.Form/Private/Templates/Form/Email.html'
              format: html
          'Dotpulse.Form:Email':
            implementationClassName: 'Dotpulse\Form\Finishers\EmailFinisher'
            options:
              templatePathAndFilename: 'resource://Dotpulse.Form/Private/Templates/Form/Email.html'
              format: html
          'Dotpulse.Form:EmailWithAttachment':
            implementationClassName: 'Dotpulse\Form\Finishers\EmailWithAttachmentFinisher'
            options:
              templatePathAndFilename: 'resource://Dotpulse.Form/Private/Templates/Form/Email.html'
              format: html
          'Dotpulse.Form:SaveToDatabase':
            implementationClassName: 'Dotpulse\Form\Finishers\SaveToDatabaseFinisher'
            options: {}

      bootstrap:
        parentPreset: 'default'
        title: 'Bootstrap by Dotpulse'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Dotpulse.Form/Private/Layouts/Bootstrap/{@type}.html'
              partialPathPattern: 'resource://Dotpulse.Form/Private/Partials/Bootstrap/{@type}.html'
          'TYPO3.Form:Page':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Bootstrap/Page.html'
          'TYPO3.Form:Form':
            renderingOptions:
              buttonContainerClass: 'form-footer'
          'TYPO3.Form:FormElement':
            properties:
              containerClassAttribute: 'form-group'
              errorClassAttribute: 'has-danger'
          'TYPO3.Form:SingleLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:Checkbox':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Bootstrap/Checkbox.html'
            properties:
              containerClassAttribute: 'checkbox'
          'TYPO3.Form:MultipleSelectCheckboxes':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Bootstrap/MultipleSelectCheckboxes.html'
            properties:
              elementClassAttribute: 'checkbox-inline'
          'TYPO3.Form:SingleSelectRadiobuttons':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Bootstrap/SingleSelectRadiobuttons.html'
            properties:
              elementClassAttribute: 'radio-inline'
          'TYPO3.Form:MultipleSelectDropdown':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:SingleSelectionMixin':
            properties:
              elementClassAttribute: 'form-control'
          'Dotpulse.Form:Submit':
            properties:
              containerClassAttribute: 'form-group'

      foundation:
        parentPreset: 'default'
        title: 'Foundation by Dotpulse'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Dotpulse.Form/Private/Layouts/Foundation/{@type}.html'
              partialPathPattern: 'resource://Dotpulse.Form/Private/Partials/Foundation/{@type}.html'
          'TYPO3.Form:Page':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Foundation/Page.html'
          'TYPO3.Form:Form':
            renderingOptions:
              buttonContainerClass: 'form-footer'
              previousButtonClass: 'button alert'
              nextButtonClass: 'button'
              submitButtonClass: 'button'
          'TYPO3.Form:FormElement':
            properties:
              containerClassAttribute: 'form-group'
              errorClassAttribute: 'is-invalid-label'
              elementErrorClassAttribute: 'is-invalid-input'
              colClassAttribute: 'columns small-6'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: ''
          'TYPO3.Form:Checkbox':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Foundation/Checkbox.html'
          'TYPO3.Form:MultipleSelectCheckboxes':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Foundation/MultipleSelectCheckboxes.html'
          'TYPO3.Form:SingleSelectRadiobuttons':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Foundation/SingleSelectRadiobuttons.html'
          'Dotpulse.Form:Submit':
            properties:
              containerClassAttribute: 'form-group'
              elementClassAttribute: 'button'
          'Dotpulse.Form:Column':
            properties:
              colClassAttribute: 'columns small-6'

      material:
        parentPreset: 'default'
        title: 'Material by Dotpulse'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Dotpulse.Form/Private/Layouts/Material/{@type}.html'
              partialPathPattern: 'resource://Dotpulse.Form/Private/Partials/Material/{@type}.html'
          'TYPO3.Form:Page':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Material/Page.html'
          'TYPO3.Form:Form':
            renderingOptions:
              buttonContainerClass: 'form-footer'
              previousButtonClass: 'btn btn-lg btn-default'
              nextButtonClass: 'btn btn-lg btn-primary'
              submitButtonClass: 'btn btn-lg btn-primary'
          'TYPO3.Form:FormElement':
            properties:
              containerClassAttribute: 'form-group'
              errorClassAttribute: 'has-danger'
              rowClassAttribute: 'row form-row'
          'TYPO3.Form:SingleLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:Checkbox':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Material/Checkbox.html'
            properties:
              containerClassAttribute: 'form-checkbox'
              elementClassAttribute: 'checkbox'
          'TYPO3.Form:MultipleSelectCheckboxes':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Material/MultipleSelectCheckboxes.html'
            properties:
              containerClassAttribute: 'form-checkbox form-checkbox-inline'
              elementClassAttribute: 'checkbox'
              renderLabel: TRUE
          'TYPO3.Form:SingleSelectRadiobuttons':
            renderingOptions:
              templatePathPattern: 'resource://Dotpulse.Form/Private/Templates/Form/Material/SingleSelectRadiobuttons.html'
            properties:
              containerClassAttribute: 'form-radio form-radio-inline'
              elementClassAttribute: 'radio'
              renderLabel: TRUE
          'TYPO3.Form:MultipleSelectDropdown':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:SingleSelectDropdown':
            properties:
              containerClassAttribute: 'form-group form-select'
              elementClassAttribute: 'styled'
          'Dotpulse.Form:Submit':
            properties:
              containerClassAttribute: 'form-group'
              elementClassAttribute: 'btn btn-lg btn-primary'
